// Publishers
export const REQ_PUBLISHERS_PENDING = 'REQ_PUBLISHERS_PENDING' as const;
export const REQ_PUBLISHERS_SUCCESS = 'REQ_PUBLISHERS_SUCCESS' as const;
export const REQ_PUBLISHERS_ERROR = 'REQ_PUBLISHERS_ERROR' as const;
export const REQ_PUBLISHER_PENDING = 'REQ_PUBLISHER_PENDING' as const;
export const REQ_PUBLISHER_SUCCESS = 'REQ_PUBLISHER_SUCCESS' as const;
export const REQ_PUBLISHER_ERROR = 'REQ_PUBLISHER_ERROR' as const;
export const ADD_PUBLISHER_PENDING = 'ADD_PUBLISHER_PENDING' as const;
export const ADD_PUBLISHER_SUCCESS = 'ADD_PUBLISHER_SUCCESS' as const;
export const ADD_PUBLISHER_ERROR = 'ADD_PUBLISHER_ERROR' as const;
export const UPDATE_PUBLISHER_PENDING = 'UPDATE_PUBLISHER_PENDING' as const;
export const UPDATE_PUBLISHER_SUCCESS = 'UPDATE_PUBLISHER_SUCCESS' as const;
export const UPDATE_PUBLISHER_ERROR = 'UPDATE_PUBLISHER_ERROR' as const;
export const DELETE_PUBLISHER_PENDING = 'DELETE_PUBLISHER_PENDING' as const;
export const DELETE_PUBLISHER_SUCCESS = 'DELETE_PUBLISHER_SUCCESS' as const;
export const DELETE_PUBLISHER_ERROR = 'DELETE_PUBLISHER_ERROR' as const;

// Comic Books
export const REQ_COMIC_BOOKS_PENDING = 'REQ_COMIC_BOOKS_PENDING' as const;
export const REQ_COMIC_BOOKS_SUCCESS = 'REQ_COMIC_BOOKS_SUCCESS' as const;
export const REQ_COMIC_BOOKS_ERROR = 'REQ_COMIC_BOOKS_ERROR' as const;
export const REQ_COMIC_BOOK_PENDING = 'REQ_COMIC_BOOK_PENDING' as const;
export const REQ_COMIC_BOOK_SUCCESS = 'REQ_COMIC_BOOK_SUCCESS' as const;
export const REQ_COMIC_BOOK_ERROR = 'REQ_COMIC_BOOK_ERROR' as const;
export const ADD_COMIC_BOOK_PENDING = 'ADD_COMIC_BOOK_PENDING' as const;
export const ADD_COMIC_BOOK_SUCCESS = 'ADD_COMIC_BOOK_SUCCESS' as const;
export const ADD_COMIC_BOOK_ERROR = 'ADD_COMIC_BOOK_ERROR' as const;
export const UPDATE_COMIC_BOOK_PENDING = 'UPDATE_COMIC_BOOK_PENDING' as const;
export const UPDATE_COMIC_BOOK_SUCCESS = 'UPDATE_COMIC_BOOK_SUCCESS' as const;
export const UPDATE_COMIC_BOOK_ERROR = 'UPDATE_COMIC_BOOK_ERROR' as const;
export const DELETE_COMIC_BOOK_PENDING = 'DELETE_COMIC_BOOK_PENDING' as const;
export const DELETE_COMIC_BOOK_SUCCESS = 'DELETE_COMIC_BOOK_SUCCESS' as const;
export const DELETE_COMIC_BOOK_ERROR = 'DELETE_COMIC_BOOK_ERROR' as const;

// Comic Book Titles
export const REQ_COMIC_BOOK_TITLES_PENDING = 'REQ_COMIC_BOOK_TITLES_PENDING' as const;
export const REQ_COMIC_BOOK_TITLES_SUCCESS = 'REQ_COMIC_BOOK_TITLES_SUCCESS' as const;
export const REQ_COMIC_BOOK_TITLES_ERROR = 'REQ_COMIC_BOOK_TITLES_ERROR' as const;
export const REQ_COMIC_BOOK_TITLE_PENDING = 'REQ_COMIC_BOOK_TITLE_PENDING' as const;
export const REQ_COMIC_BOOK_TITLE_SUCCESS = 'REQ_COMIC_BOOK_TITLE_SUCCESS' as const;
export const REQ_COMIC_BOOK_TITLE_ERROR = 'REQ_COMIC_BOOK_TITLE_ERROR' as const;
export const ADD_COMIC_BOOK_TITLE_PENDING = 'ADD_COMIC_BOOK_TITLE_PENDING' as const;
export const ADD_COMIC_BOOK_TITLE_SUCCESS = 'ADD_COMIC_BOOK_TITLE_SUCCESS' as const;
export const ADD_COMIC_BOOK_TITLE_ERROR = 'ADD_COMIC_BOOK_TITLE_ERROR' as const;
export const UPDATE_COMIC_BOOK_TITLE_PENDING = 'UPDATE_COMIC_BOOK_TITLE_PENDING' as const;
export const UPDATE_COMIC_BOOK_TITLE_SUCCESS = 'UPDATE_COMIC_BOOK_TITLE_SUCCESS' as const;
export const UPDATE_COMIC_BOOK_TITLE_ERROR = 'UPDATE_COMIC_BOOK_TITLE_ERROR' as const;
export const DELETE_COMIC_BOOK_TITLE_PENDING = 'DELETE_COMIC_BOOK_TITLE_PENDING' as const;
export const DELETE_COMIC_BOOK_TITLE_SUCCESS = 'DELETE_COMIC_BOOK_TITLE_SUCCESS' as const;
export const DELETE_COMIC_BOOK_TITLE_ERROR = 'DELETE_COMIC_BOOK_TITLE_ERROR' as const;

// Users
export const REQ_USERS_PENDING = 'REQ_USERS_PENDING' as const;
export const REQ_USERS_SUCCESS = 'REQ_USERS_SUCCESS' as const;
export const REQ_USERS_ERROR = 'REQ_USERS_ERROR' as const;
export const REQ_USER_PENDING = 'REQ_USER_PENDING' as const;
export const REQ_USER_SUCCESS = 'REQ_USER_SUCCESS' as const;
export const REQ_USER_ERROR = 'REQ_USER_ERROR' as const;
export const ADD_USER_PENDING = 'ADD_USER_PENDING' as const;
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS' as const;
export const ADD_USER_ERROR = 'ADD_USER_ERROR' as const;
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING' as const;
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS' as const;
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR' as const;
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING' as const;
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS' as const;
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR' as const;

// User Profile
export const REQ_USER_PROFILE_PENDING = 'REQ_USER_PROFILE_PENDING' as const;
export const REQ_USER_PROFILE_SUCCESS = 'REQ_USER_PROFILE_SUCCESS' as const;
export const REQ_USER_PROFILE_ERROR = 'REQ_USER_PROFILE_ERROR' as const;

// Authentication
export const REQ_LOGIN_PENDING = 'REQ_LOGIN_PENDING' as const;
export const REQ_LOGIN_SUCCESS = 'REQ_LOGIN_SUCCESS' as const;
export const REQ_LOGIN_ERROR = 'REQ_LOGIN_ERROR' as const;
export const REQ_USER_LOGOUT = 'REQ_USER_LOGOUT' as const;

// Email Password Reset
export const REQ_EMAILPASSWORDRESET_PENDING = 'EMAILPASSWORDRESET_PENDING' as const;
export const REQ_EMAILPASSWORDRESET_SUCCESS = 'EMAILPASSWORDRESET_SUCCESS' as const;
export const REQ_EMAILPASSWORDRESET_ERROR = 'EMAILPASSWORDRESET_ERROR' as const;

// Password Reset
export const REQ_PASSWORDRESET_PENDING = 'PASSWORDRESET_PENDING' as const;
export const REQ_PASSWORDRESET_SUCCESS = 'PASSWORDRESET_SUCCESS' as const;
export const REQ_PASSWORDRESET_ERROR = 'PASSWORDRESET_ERROR' as const;
export const UPDATE_PASSWORDRESET_PENDING = 'UPDATE_PASSWORDRESET_PENDING' as const;
export const UPDATE_PASSWORDRESET_SUCCESS = 'UPDATE_PASSWORDRESET_SUCCESS' as const;
export const UPDATE_PASSWORDRESET_ERROR = 'UPDATE_PASSWORDRESET_ERROR' as const;

// Messaging
export const REQ_MESSAGINGS_PENDING = 'REQ_MESSAGINGS_PENDING' as const;
export const REQ_MESSAGINGS_SUCCESS = 'REQ_MESSAGINGS_SUCCESS' as const;
export const REQ_MESSAGINGS_SENT_SUCCESS = 'REQ_MESSAGINGS_SENT_SUCCESS' as const;
export const REQ_MESSAGINGS_ERROR = 'REQ_MESSAGINGS_ERROR' as const;
export const REQ_MESSAGING_PENDING = 'REQ_MESSAGING_PENDING' as const;
export const REQ_MESSAGING_SUCCESS = 'REQ_MESSAGING_SUCCESS' as const;
export const REQ_MESSAGING_ERROR = 'REQ_MESSAGING_ERROR' as const;
export const ADD_MESSAGING_PENDING = 'ADD_MESSAGING_PENDING' as const;
export const ADD_MESSAGING_SUCCESS = 'ADD_MESSAGING_SUCCESS' as const;
export const ADD_MESSAGING_ERROR = 'ADD_MESSAGING_ERROR' as const;
export const UPDATE_MESSAGING_PENDING = 'UPDATE_MESSAGING_PENDING' as const;
export const UPDATE_MESSAGING_SUCCESS = 'UPDATE_MESSAGING_SUCCESS' as const;
export const UPDATE_MESSAGING_ERROR = 'UPDATE_MESSAGING_ERROR' as const;
export const DELETE_MESSAGE_PENDING = 'DELETE_MESSAGE_PENDING' as const;
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS' as const;
export const DELETE_MESSAGE_ERROR = 'DELETE_MESSAGE_ERROR' as const;

// Sales
export const REQ_SALE_COMICS_PENDING = 'REQ_SALE_COMICS_PENDING' as const;
export const REQ_SALE_COMICS_SUCCESS = 'REQ_SALE_COMICS_SUCCESS' as const;
export const REQ_SALE_COMICS_ERROR = 'REQ_SALE_COMICS_ERROR' as const;
export const REQ_SALE_COMIC_PENDING = 'REQ_SALE_COMIC_PENDING' as const;
export const REQ_SALE_COMIC_SUCCESS = 'REQ_SALE_COMIC_SUCCESS' as const;
export const REQ_SALE_COMIC_ERROR = 'REQ_SALE_COMIC_ERROR' as const;
export const ADD_SALE_COMIC_PENDING = 'ADD_SALE_COMIC_PENDING' as const;
export const ADD_SALE_COMIC_SUCCESS = 'ADD_SALE_COMIC_SUCCESS' as const;
export const ADD_SALE_COMIC_ERROR = 'ADD_SALE_COMIC_ERROR' as const;
export const UPDATE_SALE_COMIC_PENDING = 'UPDATE_SALE_COMIC_PENDING' as const;
export const UPDATE_SALE_COMIC_SUCCESS = 'UPDATE_SALE_COMIC_SUCCESS' as const;
export const UPDATE_SALE_COMIC_ERROR = 'UPDATE_SALE_COMIC_ERROR' as const;
export const DELETE_SALE_COMIC_PENDING = 'DELETE_SALE_COMIC_PENDING' as const;
export const DELETE_SALE_COMIC_SUCCESS = 'DELETE_SALE_COMIC_SUCCESS' as const;
export const DELETE_SALE_COMIC_ERROR = 'DELETE_SALE_COMIC_ERROR' as const;
export const REQ_SALE_ALL_COMICS_PENDING = 'REQ_SALE_ALL_COMICS_PENDING' as const;
export const REQ_SALE_ALL_COMICS_SUCCESS = 'REQ_SALE_ALL_COMICS_SUCCESS' as const;
export const REQ_SALE_ALL_COMICS_ERROR = 'REQ_SALE_ALL_COMICS_ERROR' as const;

// Wishlist
export const REQ_WISHLIST_COMICS_PENDING = 'REQ_WISHLIST_COMICS_PENDING' as const;
export const REQ_WISHLIST_COMICS_SUCCESS = 'REQ_WISHLIST_COMICS_SUCCESS' as const;
export const REQ_WISHLIST_COMICS_ERROR = 'REQ_WISHLIST_COMICS_ERROR' as const;
export const REQ_WISHLIST_COMIC_PENDING = 'REQ_WISHLIST_COMIC_PENDING' as const;
export const REQ_WISHLIST_COMIC_SUCCESS = 'REQ_WISHLIST_COMIC_SUCCESS' as const;
export const REQ_WISHLIST_COMIC_ERROR = 'REQ_WISHLIST_COMIC_ERROR' as const;
export const ADD_WISHLIST_COMIC_PENDING = 'ADD_WISHLIST_COMIC_PENDING' as const;
export const ADD_WISHLIST_COMIC_SUCCESS = 'ADD_WISHLIST_COMIC_SUCCESS' as const;
export const ADD_WISHLIST_COMIC_ERROR = 'ADD_WISHLIST_COMIC_ERROR' as const;
export const UPDATE_WISHLIST_COMIC_PENDING = 'UPDATE_WISHLIST_COMIC_PENDING' as const;
export const UPDATE_WISHLIST_COMIC_SUCCESS = 'UPDATE_WISHLIST_COMIC_SUCCESS' as const;
export const UPDATE_WISHLIST_COMIC_ERROR = 'UPDATE_WISHLIST_COMIC_ERROR' as const;
export const DELETE_WISHLIST_COMIC_PENDING = 'DELETE_WISHLIST_COMIC_PENDING' as const;
export const DELETE_WISHLIST_COMIC_SUCCESS = 'DELETE_WISHLIST_COMIC_SUCCESS' as const;
export const DELETE_WISHLIST_COMIC_ERROR = 'DELETE_WISHLIST_COMIC_ERROR' as const;